<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuotationPortal.Domain\QuotationPortal.Domain.csproj" />
    <ProjectReference Include="..\QuotationPortal.Infrastrcuture\QuotationPortal.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
    <Folder Include="Mappers\" />
    <Folder Include="Services\" />
    <Folder Include="Validators\" />
  </ItemGroup>

</Project>
