name: Deployment

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/deployment.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: print message
        run: echo "Running deployment workflow"